version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: financial-balance-postgres
    environment:
      POSTGRES_DB: ${DATABASE_DB:-data_base}
      POSTGRES_USER: ${DATABASE_USER:-user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    networks:
      - financial-balance-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: financial-balance-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "5050:80"
    networks:
      - financial-balance-network

networks:
  financial-balance-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local